defaults:
  - model/pi0_5@model
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REPO_PATH}/examples/embodiment/config

convertor:
  save_path: /workspace/RLinf/ckpt
  merge_lora_weighs: False

  ckpt_path: /data/logs/20260315-14:01:52/test_openpi/checkpoints/global_step_10000/actor/model_state_dict/full_weights.pt

# Override the default values in model/openvla_oft
model:
  model_type: "openpi"
  model_path: "/workspace/RLinf/ManiSkill-GS/RLinf-Pi05-GSEnv-PutCubeOnPlate-V0-SFT"

  unnorm_key: bridge_orig
  is_lora: False
  lora_rank: 32
  # lora_path: /path/to/RLinf-OpenVLAOFT-LIBERO-130-Base-Lora/lora_adapter
  max_prompt_length: 30
