model_type: "openpi"

# Model path - should be set in specific config files
model_path: "/path/to/model/openpi"

precision: null # for openpi, precision is null, please do not change this value

# Action and chunk settings
num_action_chunks: 10
action_dim: 7

# LoRA settings
is_lora: False
lora_rank: 32

# Training settings
use_proprio: True
num_steps: 5
add_value_head: True

# openpi specific parameters
openpi:
  config_name: "pi05_gsenv"
  num_images_in_input: 2
  noise_level: 0.5
  train_expert_only: True
  noise_method: "flow_sde"
  value_after_vlm: False
  value_vlm_mode: "mean_token"
  detach_critic_input: null
  action_chunk: 5
  num_steps: 5
  action_env_dim: 7
  add_value_head: True